export default {
  timeUnit: { second: "s", minute: "m", hour: "h" },
  common: {
    ok: "OK!",
    cancel: "Cancel",
    back: "Back",
    logOut: "Log Out",
    required: "Required",
    optional: "Optional",
    change: "Change",
    edit: "Edit",
    goBack: "<< Go Back",
    confirm: "Confirm",
    submit: "Submit",
  },
  tab: {
    tabDashboard: "Dashboard",
    tabFormCreation: "Form Creation",
    tabMyPage: "My Page",
    tabTop: "TOP",
  },
  emptyStateComponent: {
    generic: {
      heading: "So empty... so sad",
      content:
        "No data found yet. Try clicking the button to refresh or reload the app.",
      button: "Let's try this again",
    },
  },
  errorScreen: {
    title: "Something went wrong!",
    reset: "RESET APP",
    friendlySubtitle:
      "This is the screen that your users will see in production when an error is thrown. You'll want to customize this message (located in `app/i18n/en.ts`) and probably the layout as well (`app/screens/ErrorScreen`). If you want to remove this entirely, check `app/app.tsx` for the <ErrorBoundary> component.",
  },
  loginScreen: {
    example: "Example",
    password: "Password",
    forgotPassword: "Forgot Password?",
    pressThis: "Press this",
    rememberMe: "Remember Me",
    signIn: "Sign In",
    requiredUsernameSchema: "Username is required",
    invalidEmailSchema: "Invalid email",
    requiredPasswordSchema: "Password is required",
    userNotRegisteredSchema: "User not registered",
  },
  forgotPasswordScreen: {
    title: "Forgot Password",
    usernameOrEmail: "Username or Email",
    email: "Email",
    backToLogin: "Back to Login",
    sendLink: "Send Link",
    sendLinkSuccess: "Email sent successfully",
  },
  resetPasswordScreen: {
    title: "Reset Password",
    passwordLabel: "Password",
    confirmPasswordLabel: "Confirm Password",
    buttonResetPassword: "Reset Password",
    goBackToLogin: "Go Back to Login",
    requiredPasswordSchema: "Password is required",
    requiredConfirmPasswordSchema: "Confirm Password is required",
    passwordsDontMatchSchema: "Passwords don't match",
    sessionExpired: "Session expired, please try again",
    tokenInvalidOrExpired: "Token invalid or expired, please try again",
  },
  logoutScreen: {
    goToLoginScreen: "Go to Login Screen",
    logoutTitle: "Logout",
    thanksForUsing: "Thanks for using",
  },
  welcomeScreen: { goNext: "Go Next" },
  complete: {
    title: "パスワード再設定",
    content: "パスワードを再設定しました。",
  },
  myPageScreen: {
    basicInfo: "Basic Information",
    emailTitle: "Email",
    username: "Username",
    password: "Password",
    setting: "Setting",
    settingLanguage: "Setting Language",
    solution: "Solution",
    displayName: "Display Name",
    affiliationInfo: "所属情報",
    departmentName: "部署名",
    director: "役職",
    timezone: "タイムゾーン",
    numberDigit: "数値桁区切り形式",
  },
  dashboardScreen: {
    approved: "Approved",
    approving: "Approving",
    typing: "Typing",
    sendBack: "Send Back",
    latestInputResult: "Latest Input Result",
    dashboard: "Dashboard",
  },
  formCreationScreen: { formCreation: "Form Creation" },
  formTitleScreen: {
    saveLoginState: "Save Login State",
    keep: "Keep",
    contentConfirmation: "Content Confirmation",
  },
  notificationListScreen: {
    title: "Notification List",
    remand: "Remand",
    approved: "Approved",
    typing: "Typing",
    acknowledged: "Acknowledged",
  },
  reviewFeedbackScreen: { title: "Review Feedback" },
  editDataScreen: {
    title: "Edit Data",
    latestInputResult: "Latest Input Result",
    advancedSearch: "Advanced Search",
    detail: "Detail",
  },
  demoPodcastListScreen: {
    title: "React Native Radio episodes",
    onlyFavorites: "Only Show Favorites",
    favoriteButton: "Favorite",
    unfavoriteButton: "Unfavorite",
    accessibility: {
      cardHint:
        "Double tap to listen to the episode. Double tap and hold to {{action}} this episode.",
      switch: "Switch on to only show favorites",
      favoriteAction: "Toggle Favorite",
      favoriteIcon: "Episode not favorited",
      unfavoriteIcon: "Episode favorited",
      publishLabel: "Published {{date}}",
      durationLabel:
        "Duration: {{hours}} hours {{minutes}} minutes {{seconds}} seconds",
    },
    noFavoritesEmptyState: {
      heading: "This looks a bit empty",
      content:
        "No favorites have been added yet. Tap the heart on an episode to add it to your favorites!",
    },
  },
  viewDataDetailScreen: {
    title: "Title",
    titleComment: "Title Comment",
    subtitle: "Subtitle",
    approvalStatus: "Approval Status",
    fileReference: "File Reference",
    basicInformation: "Basic Information",
    equipmentInformation: "Equipment Information",
    employmentInformation: "Employment Information",
    viewComments: "View Comments",
    edit: "Edit",
    deletion: "Deletion",
    comment: "Comment",
  },
};
