import { Translations } from "./ja"

const en: Translations = {
  timeUnit: {
    hour: "h",
    minute: "m",
    second: "s",
  },
  common: {
    ok: "OK!",
    cancel: "Cancel",
    back: "Back",
    logOut: "Log Out",
    change: "Change",
    edit: "Edit",
    required: "Required",
    optional: "Optional",
    goBack: "<< Go Back",
    confirm: "Confirm",
    submit: "Submit",
  },
  welcomeScreen: {
    goNext: "Go Next",
  },
  complete: {
    title: "パスワード再設定",
    content: "パスワードを再設定しました。",
  },
  viewDataDetailScreen: {
    approvalStatus: "Approval Status",
    basicInformation: "Basic Information",
    comment: "Comment",
    deletion: "Deletion",
    edit: "Edit",
    employmentInformation: "Employment Information",
    equipmentInformation: "Equipment Information",
    fileReference: "File Reference",
    subtitle: "Subtitle",
    title: "Title",
    titleComment: "Title Comment",
    viewComments: "View Comments",
  },
  errorScreen: {
    title: "Something went wrong!",
    friendlySubtitle:
      "This is the screen that your users will see in production when an error is thrown. You'll want to customize this message (located in `app/i18n/en.ts`) and probably the layout as well (`app/screens/ErrorScreen`). If you want to remove this entirely, check `app/app.tsx` for the <ErrorBoundary> component.",
    reset: "RESET APP",
  },
  emptyStateComponent: {
    generic: {
      heading: "So empty... so sad",
      content: "No data found yet. Try clicking the button to refresh or reload the app.",
      button: "Let's try this again",
    },
  },
  loginScreen: {
    example: "Example",
    signIn: "Sign In",
    forgotPassword: "Forgot Password?",
    pressThis: "Press this",
    rememberMe: "Remember Me",
    password: "Password",
    invalidEmailSchema: "Invalid email",
    requiredPasswordSchema: "Password is required",
    requiredUsernameSchema: "Username is required",
    userNotRegisteredSchema: "User not registered",
  },
  forgotPasswordScreen: {
    backToLogin: "Back to Login",
    sendLink: "Send Link",
    title: "Forgot Password",
    usernameOrEmail: "Username or Email",
    email: "Email",
    sendLinkSuccess: "Email sent successfully",
  },
  resetPasswordScreen: {
    buttonResetPassword: "Reset Password",
    confirmPasswordLabel: "Confirm Password",
    goBackToLogin: "Go Back to Login",
    passwordLabel: "Password",
    passwordsDontMatchSchema: "Passwords don't match",
    requiredConfirmPasswordSchema: "Confirm Password is required",
    requiredPasswordSchema: "Password is required",
    title: "Reset Password",
    sessionExpired: "Session expired, please try again",
    tokenInvalidOrExpired: "Token invalid or expired, please try again",
  },
  demoPodcastListScreen: {
    title: "React Native Radio episodes",
    onlyFavorites: "Only Show Favorites",
    favoriteButton: "Favorite",
    unfavoriteButton: "Unfavorite",
    accessibility: {
      cardHint:
        "Double tap to listen to the episode. Double tap and hold to {{action}} this episode.",
      switch: "Switch on to only show favorites",
      favoriteAction: "Toggle Favorite",
      favoriteIcon: "Episode not favorited",
      unfavoriteIcon: "Episode favorited",
      publishLabel: "Published {{date}}",
      durationLabel: "Duration: {{hours}} hours {{minutes}} minutes {{seconds}} seconds",
    },
    noFavoritesEmptyState: {
      heading: "This looks a bit empty",
      content:
        "No favorites have been added yet. Tap the heart on an episode to add it to your favorites!",
    },
  },
  dashboardScreen: {
    approved: "Approved",
    approving: "Approving",
    dashboard: "Dashboard",
    latestInputResult: "Latest Input Result",
    sendBack: "Send Back",
    typing: "Typing",
  },
  formCreationScreen: {
    formCreation: "Form Creation",
  },
  formTitleScreen: {
    contentConfirmation: "Content Confirmation",
    keep: "Keep",
    saveLoginState: "Save Login State",
  },
  myPageScreen: {
    basicInfo: "Basic Information",
    emailTitle: "Email",
    password: "Password",
    setting: "Setting",
    settingLanguage: "Setting Language",
    solution: "Solution",
    username: "Username",
    displayName: "Display Name",
    affiliationInfo: "所属情報",
    departmentName: "部署名",
    director: "役職",
    timezone: "タイムゾーン",
    numberDigit: "数値桁区切り形式",
  },
  logoutScreen: {
    goToLoginScreen: "Go to Login Screen",
    logoutTitle: "Logout",
    thanksForUsing: "Thanks for using",
  },
  tab: {
    tabDashboard: "Dashboard",
    tabFormCreation: "Form Creation",
    tabMyPage: "My Page",
    tabTop: "TOP",
  },
  editDataScreen: {
    advancedSearch: "Advanced Search",
    detail: "Detail",
    latestInputResult: "Latest Input Result",
    title: "Edit Data",
  },
  notificationListScreen: {
    acknowledged: "Acknowledged",
    approved: "Approved",
    remand: "Remand",
    title: "Notification List",
    typing: "Typing",
  },
  reviewFeedbackScreen: {
    title: "Review Feedback",
  },
}

export default en
